### ISSUE TITLE
Problema con el valor mínimo de los Attrs

### ISSUE THREAD

**Issue by Anubis-13** [jlararigger/jlr_sort_attributes#1]
Hola Juan , primero gran trabajo. es algo muy necesario para Maya. Soy Jero. Bueno el problema me pasa cuando muevo de posición cualquier attr se van los datos guardados como valor mínimo en los attrs.Por lo demas me va de lujo gracias por el plugin. Tengo la versión 2020.4

**Comment by jlararigger** [comment]
Hola Jero,

Gracias por el aviso. Miro a ver que está pasando.

**Comment by jlararigger** [comment]
Hola Jero,

Gracias por el feedback. Ya he subido una versión con este problema arreglado. ;)
