### ISSUE TITLE
Problema con el valor mínimo y máximo de los Attrs

### ISSUE THREAD

**Issue by Anubis-13** [jlararigger/jlr_sort_attributes#3]
Hola Juan , soy Jero. Que casualidad con lo del corto te vi ayer y ahora te escribo. Es otra vez casi el mismo problema, solo que en esta ocasión es cuando creo nuevo attr con comando python con el flag añadido de "at= short". Una vez creado me funciona y al usar subir el attr pierde su máximo y mínimo. Se deselecciona como la otra vez, solo que el problema es distinto.  Lo dicho solo me pasa cuando hago esto por lo demás me encanta lo uso mucho es un plugin muy necesario.
Este es el comando
cmds.addAttr (sn = 'String', ln = 'String', min = 0, max = 1, dv = 1, k = True, at = 'short' )

si uso at = long funciona bien, si lo hago manual y marco integer también funciona bien, no he probado con mas. Espero te pueda ayudar por si quieres echarle un ojo. Saludos.

**Comment by jlararigger** [comment]
Hola Jero. Me hizo ilusión verte por allí. Gracias por el feedback. Ya está arreglado, he subido un fix con este problema arreglado.
